const data = [
    {
        id: 1,
        name: "BLEACHED PUNK",
        artist: "KAOS07",
        price: 6500,
        img: `assets/img/tapa1.jpg`,
        stock: 20,
    },
    {
        id: 2,
        name: "Power To The Soul",
        artist: "Chlär",
        price: 3200,
        img: "assets/img/tapa2.jpg",
        stock: 16,
    },
    {
        id: 3,
        name: "HEARTCORE ESSENTIALS",
        artist: "KAOS08",
        price: 4700,
        img: "assets/img/tapa3.jpg",
        stock: 6,
    },
    {
        id: 4,
        name: "Juicy",
        artist: "Julian Muller",
        price: 4100,
        img: "assets/img/tapa4.jpg",
        stock: 1,
    },
    {
        id: 5,
        name: "Strange Days",
        artist: "Slam",
        price: 3700,
        img: "assets/img/tapa5.jpg",
        stock: 8,
    },
    {
        id: 6,
        name: "Disparate Lines",
        artist: "Axel Karakasis",
        price: 3200,
        img: "assets/img/tapa6.jpg",
        stock: 4,
    },
    {
        id: 7,
        name: "Mögen",
        artist: "TBK006",
        price: 2900,
        img: "assets/img/tapa7.jpg",
        stock: 28,
    },
    {
        id: 8,
        name: "TRANSFORMA VOLUME FIVE",
        artist: "A.Paul, DJ Dextro",
        price: 4300,
        img: "assets/img/tapa8.jpg",
        stock: 31,
    },
    {
        id: 9,
        name: "Many ways To Go",
        artist: "Jeroen Search",
        price: 3400,
        img: "assets/img/tapa9.jpg",
        stock: 3,
    },
    {
        id: 10,
        name: "Intermission",
        artist: "Thomas Hessler",
        price: 2400,
        img: "assets/img/tapa10.jpg",
        stock: 8,
    },
    {
        id: 11,
        name: "LOSDOSMILDOS",
        artist: "COYU",
        price: 5400,
        img: "assets/img/tapa11.jpg",
        stock: 11,
    },
    {
        id: 12,
        name: "Traces Of Influences",
        artist: "Hertz, Mhonolink",
        price: 4300,
        img: "assets/img/tapa12.jpg",
        stock: 15,
    },
    {
        id: 13,
        name: "Evolving",
        artist: "A-STS",
        price: 2000,
        img: "assets/img/tapa13.jpg",
        stock: 0,
    },
    {
        id: 14,
        name: "Manifesto Raw Culture",
        artist: "Various Artists",
        price: 2900,
        img: "assets/img/tapa14.jpg",
        stock: 4,
    },
    {
        id: 15,
        name: "Techwise & Otherwise",
        artist: "Devilfish",
        price: 5100,
        img: "assets/img/tapa15.jpg",
        stock: 9,
    },
    {
        id: 16,
        name: "Never Mind Have Fun",
        artist: "M.I.T.A.",
        price: 4500,
        img: "assets/img/tapa16.jpg",
        stock: 7,
    },
    {
        id: 17,
        name: "Metaroots 2",
        artist: "SCOM047",
        price: 3500,
        img: "assets/img/tapa17.jpg",
        stock: 25,
    },
    {
        id: 18,
        name: "Planet MHz III",
        artist: "MHZ003",
        price: 2700,
        img: "assets/img/tapa18.jpg",
        stock: 13,
    },
    {
        id: 19,
        name: "Third Eye",
        artist: "Florian Meindl",
        price: 4000,
        img: "assets/img/tapa19.jpg",
        stock: 17,
    },
    {
        id: 20,
        name: "Masquerade",
        artist: "A.Morgan",
        price: 3200,
        img: "assets/img/tapa20.jpg",
        stock: 10,
    }
]
export default data;